[build]
command = "npx prisma generate && npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache"

  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"
