[build]
command = "npx prisma generate && npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"
[headers.values]
Cache-Control = "public, max-age=300"

[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "no-cache"


[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "max-age=300"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "max-age=300"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "max-age=0, must-revalidate"

# Remove or comment out this section if it's not needed
# [[redirects]]
# from = "*.js"
# to = "/index.html"
# status = 200



